### ISSUE TITLE
Untagged text from former "iml:TITLE"

### ISSUE THREAD

**Issue by joeytakeda** [internetshakespeare/ise2-import#5]
From iseMV_F1.xml:

```
<!--FIXME: "TITLE" markup was used here in IML; is there any formatting worth recording?-->The Merchant of Venice.<figure type="rule"/>
```
Should this be made a comment? Or is this purposefully invalid so that an editor will later fix it?

**Comment by telic** [comment]
I don't know if there is a good way we can consistently transform these in OS texts, so yes, I left it for an editor to fix later. TITLE's often can't be transformed into `<head>` because of other content before or after (as in this example, there is a following scene leader marked up as a `head` in the same `div`)
